
spring:
  application:
    name: demo
  cache:
    type: none


logging:
  level:
    ROOT: INFO
    com.amazonaws: DEBUG


service:
  metrics:
    dropwizard:
      enabled: true
    prometheus:
      enabled: false
  git:
    enabled: false
  vip:
    enabled: false
  swagger:
    enabled: false
  jsonp:
    enabled: false

memcached:
  cache:
    servers: solrx401p.stag.ch4.s.com:11111
    mode: static


management:
  security:
    enabled: false

hystrix:
  command:
    helloCommandKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        requestVolumeThreshold: 4
        sleepWindowInMilliseconds: 60000
      metrics:
        rollingStats:
          timeInMilliseconds: 180000
  threadpool:
    helloThreadPoolKey:
      coreSize: 30
      metrics:
        rollingStats:
          timeInMilliseconds:18000

