---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello
spec:
  ports:
  - port: 8080
    nodePort: 30037
    name: server
  selector:
    app: hello
  type: NodePort